jobs: 100
latency-wait: 150

cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --parsable
    --job-name=s.{rule}
    --partition=compute
    --nodes=1
    --ntasks=1
    --cpus-per-task={cluster.processor}
    --mem={cluster.memory}GB
    --time={cluster.walltime}
    --output=logs/{rule}/s.{rule}.o%j
    --error=logs/{rule}/s.{rule}.e%j

cluster-config: /home/fcastaneda/bin/spatial_clustering/cluster_slurm.json 

cluster-status: /home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/spatial_pilot_5k/scripts/devel/snakem_try/slurm/slurm/status-sacct.sh
jobscript: /home/fcastaneda/fcastaneda-temp/rnaseq-sc-standar/biopBal_Sara_2024/spatial_pilot_5k/scripts/devel/snakem_try/slurm/slurm/slurm-jobscript.sh

printshellcmds: True

keep-going: True

rerun-incomplete: True

local-cores: 1
max-jobs-per-second: 100
max-status-checks-per-second: 10
